{{ if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "binoculars.secretName" . }}
  labels:
    {{- include "binoculars.labels" . | nindent 4 }}
type: Opaque
data:
  dBUrl: {{ .Values.secret.dBUrl | b64enc | quote }}
  dBUser: {{ .Values.secret.dBUser | b64enc | quote }}
  dBPassword: {{ .Values.secret.dBPassword | b64enc | quote }}
{{ end }}
